config/routes.rb
Stickers::Application.routes.draw do
  resources :stickers

  

end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stickers_controller.rb
class StickersController < ApplicationController
  before_action :set_sticker, only: [:show, :edit, :update, :destroy]
	skip_before_filter  :verify_authenticity_token

  # GET /stickers
  # GET /stickers.json
  def index
    @stickers = Sticker.all
  end

  # GET /stickers/1
  # GET /stickers/1.json
  def show
  end

  # GET /stickers/new
  def new
    @sticker = Sticker.new
  end

  # GET /stickers/1/edit
  def edit
  end

  # POST /stickers
  # POST /stickers.json
  def create
    @sticker = Sticker.new(sticker_params)

    respond_to do |format|
      if @sticker.save
        format.html { redirect_to @sticker, notice: 'Sticker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sticker }
      else
        format.html { render action: 'new' }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stickers/1
  # PATCH/PUT /stickers/1.json
  def update
    respond_to do |format|
      if @sticker.update(sticker_params)
        format.html { redirect_to @sticker, notice: 'Sticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stickers/1
  # DELETE /stickers/1.json
  def destroy
    @sticker.destroy
    respond_to do |format|
      format.html { redirect_to stickers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sticker
      @sticker = Sticker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sticker_params
      params.require(:sticker).permit(:coordsX, :coordsY, :userValue)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stickers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script id = "stick-template" type = "text/html">
		<button class = "delete">X</button>
		<button class = "submit">submit</button>
		<textarea cols = "9" rows = "3" class = "txt" />
		<div class = "output"></div>
  </script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<div id = "stickerboard"></div>

</body>
</html>

app/views/stickers/_form.html.erb
<%= form_for(@sticker) do |f| %>
  <% if @sticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sticker.errors.count, "error") %> prohibited this sticker from being saved:</h2>

      <ul>
      <% @sticker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coordsX %><br>
    <%= f.number_field :coordsX %>
  </div>
  <div class="field">
    <%= f.label :coordsY %><br>
    <%= f.number_field :coordsY %>
  </div>
  <div class="field">
    <%= f.label :userValue %><br>
    <%= f.text_field :userValue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stickers/edit.html.erb
<h1>Editing sticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @sticker %> |
<%= link_to 'Back', stickers_path %>

app/views/stickers/index.html.erb
<h1>Listing stickers</h1>

<div id = "stickerboard">
</div>

<%= link_to 'New Sticker', new_sticker_path %>

app/views/stickers/new.html.erb
<h1>New sticker</h1>

<%= render 'form' %>

<%= link_to 'Back', stickers_path %>

app/views/stickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coordsx:</strong>
  <%= @sticker.coordsX %>
</p>

<p>
  <strong>Coordsy:</strong>
  <%= @sticker.coordsY %>
</p>

<p>
  <strong>Uservalue:</strong>
  <%= @sticker.userValue %>
</p>

<%= link_to 'Edit', edit_sticker_path(@sticker) %> |
<%= link_to 'Back', stickers_path %>